using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CoursesAPI.Services.Models.Entities
{
	public class CourseStudent
	{
		/// <summary>
		/// ID for CourseStudent generated by the database for each record
		/// </summary>
		public int ID { get; set; }

		/// <summary>
		/// The SSN of the student
		/// </summary>
		public string SSN { get; set; }

		/// <summary>
		/// The Course Instance ID Generated be the database for the each course instance
		/// </summary>
		public int CourseInstanceID { get; set; }

		/// <summary>
		/// Gives info about status of student in courseStudent (no records are deleted).
		/// 1: Active/registered
		/// 2: Inactive/quit
		/// </summary>
		public int Status { get; set; }

	}
}
